---
title: 'Exercise 1: Defining the Problem'
author: "Ted Laderas"
date: "April 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Scenario: Sleep Apnea and Cardiovascular Disease

You are interested in designing a study to understand the role that obstructive sleep apnea has in disease. 

Given your past knowledge, what do you expect about the relationship between sleep apnea and cardiovascular disease?

Formulate a research question about sleap apnea and cardovascular disease that you are interested in pursuing. 

## Listing Covariates

If you were to build a predictive model of cardiovascular disease (represented by a Yes or No), including sleep apnea, what would the covariate predictors be? 

Draw upon your knowledge and think about what are the most predictive risk factors associated with cardiovascular disease, including apnea.                                               
Rank these variables in terms of importance. 

## Mapping Covariates into the Data

Using your ranked list, look at the list of variables available in the Sleep Heart Health Study. Can you map your covariates into this data?

How many covariates are available? If one isn't available, is there a surrogate covariate you can use?


